apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: service-python-test3 
  janus-idp.io/tekton: service-python-test3
  backstage.io/kubernetes-id: service-python-test3
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: service-python-test3
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml