apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: service-python-test3
  janus-idp.io/tekton: service-python-test3
  backstage.io/kubernetes-id: service-python-test3
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: service-python-test3
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
